services:
  backend:
    build: ./backend
    container_name: trading-app-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev-secret-key-change-in-production
      - JWT_SECRET_KEY=dev-jwt-secret-key-change-in-production
    command: flask run --host=0.0.0.0
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: trading-app-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000/api
    depends_on:
      - backend
    command: npm start
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
